version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.0
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:
    run-task:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                name: install
                command: mvn install
            - run:
                name: test
                command: mvn test
workflows:
    run-task:
        jobs:
            - run-task
            - aws-ecs/run-task:
                  aws-access-key-id: "$AWS_ACCESS_KEY_ID"
                  cluster: default
                  task-definition: first-run-task-definition
                  subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
                  security-group-ids: $SECURITY_GROUP_IDS
                  requires:
                      - run-task
# jobs:
#   build:

#     docker:
#       - image: maven:latest
#       - image: redis:latest
#     steps:
#       - checkout

#       - run:
#           name: clean
#           command: mvn clean
#       - run:
#           name: install
#           command: mvn install
#       - run:
#           name: test
#           command: mvn test
