version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.0
    aws-ecr: circleci/aws-ecr@6.12.2
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:
    run-task:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                name: install
                command: mvn install
            - run:
                name: test
                command: mvn test
workflows:
    build-and-deploy:
        jobs:
            - run-task
            - aws-ecr/build-and-push-image:
                    repo: "spring-redis"
                    dockerfile: "../Dockerfile"
                    tag: "latest"
                    requires:
                        - run-task
            # - aws-ecs/run-task:
            #       aws-access-key-id: "$AWS_ACCESS_KEY_ID"
            #       cluster: default
            #       task-definition: first-run-task-definition
            #       subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
            #       security-group-ids: $SECURITY_GROUP_IDS
            #       requires:
            #           - run-task

