version: 2.1

orbs:
  maven: circleci/maven@0.0.12

# workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

jobs:
  build:
    docker:
      - image: maven:latest 
      - image: redis:latest
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: clean
          command: mvn clean
      - run:
          name: install
          command: mvn install
      - run: 
          name: test  
          command: mvn test