version: 2.1

# orbs:
#   maven: circleci/maven@0.0.12

# workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

jobs:
  one:
    docker:
      - image: redis:latest
   
  two:
    docker:
      - image: maven:latest 
    steps:
      - checkout
      - run:
          name: clean
          command: mvn clean
      - run:
          name: install
          command: mvn install
      - run: 
          name: test  
          command: mvn test
workflows:
  one_two:
    jobs:
      - one
      - two