version: 2.1

# orbs:
#   maven: circleci/maven@0.0.12

# workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

# jobs:
#   build:
#     machine:
#       image: ubuntu-1604:202007-01
#     steps:
#       - checkout
#       - run:
#           name: "Testing"
#           command: echo "Hi"
#       - run: 
#           name: docker-up
#           command: docker-compose up --build

#       - run: 
#           name: docker-down
#           command: docker-compose down


jobs:
  build:

    docker:
      - image: maven:latest 
      - image: redis:latest
    steps:
      - checkout
     
      # - run:
      #     name: install dockerize
      #     command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      #     environment:
      #       DOCKERIZE_VERSION: v0.3.0
      # - run:
      #     name: Wait for db
      #     command: dockerize -wait tcp://localhost:5432 -timeout 1m 
      - run:
          name: clean
          command: mvn clean
      - run:
          name: clean
          command: mvn clean
      - run:
          name: install
          command: mvn install
      - run: 
          name: test  
          command: mvn test
      