version: 2.1

# orbs:
#   maven: circleci/maven@0.0.12

# workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run: 
          name: docker
          command: docker-compose up --build


# jobs:
#   build:

#     docker:
#       - image: maven:latest 
#       - image: redis:latest
#     steps:
#       - checkout
     
#       - run:
#           name: clean
#           command: mvn clean
#       - run:
#           name: install
#           command: mvn install
#       - run: 
#           name: test  
#           command: mvn test