version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.0
    aws-ecr: circleci/aws-ecr@6.12.2
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:   
    run-task:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                name: install
                command: mvn install
            - run:
                name: test
                command: mvn test
workflows:
    build-and-deploy:
        jobs:  
            - run-task
            - aws-ecr/build-and-push-image:
                    repo: "spring-redis"
                    tag: "latest"
                    requires:
                        - run-task
            - aws-ecs/deploy-service-update:
                    requires:
                        - aws-ecr/build-and-push-image
                    family: "spring-redis"
                    cluster-name: "default"
                    container-image-name-updates: "container=spring-redis,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/spring-redis:latest"
                    verify-revision-is-deployed: true



                    
