version: 2.1

orbs:
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:
    tests:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                  name: clean
                  command: mvn clean
            - run:
                  name: install
                  command: mvn install
            - run:
                  name: test
                  command: mvn test
            - aws-ecs/run-task:
                  cluster: default
                  task-definition: first-run-task-definition:1
                  subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
                  security-group-ids: $SECURITY_GROUP_IDS
                  requires: -tests
workflows:
    run-task:
        jobs:
            - tests
          
# jobs:
#   build:

#     docker:
#       - image: maven:latest
#       - image: redis:latest
#     steps:
#       - checkout

#       - run:
#           name: clean
#           command: mvn clean
#       - run:
#           name: install
#           command: mvn install
#       - run:
#           name: test
#           command: mvn test
