version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.0
    # aws-ecs: circleci/aws-ecs@0.0.15
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:
    run-task:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                  name: install
                  command: mvn install
            - run:
                  name: test
                  command: mvn test
    update-tag:
        docker:
            - image: maven:latest
            - image: redis:latest

        steps:
            - run:
                name: test
                command: mvn spring-boot:run
            - aws-ecs/update-service:
                family: "spring-redis-service"
                cluster-name: "spring-redis-cluster"
                container-image-name-updates: "container=spring-redis-service,tag=stable"
            
workflows:
    run-task:
        jobs:
            - run-task
            - aws-ecs/run-task:
                  aws-access-key-id: "$AWS_ACCESS_KEY_ID"
                  cluster: default
                  task-definition: first-run-task-definition
                  subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
                  security-group-ids: $SECURITY_GROUP_IDS
                  requires:
                      - run-task
            - update-tag
                  requires:
                      - aws-ecs/run-task
# jobs:
#   build:

#     docker:
#       - image: maven:latest
#       - image: redis:latest
#     steps:
#       - checkout

#       - run:
#           name: clean
#           command: mvn clean
#       - run:
#           name: install
#           command: mvn install
#       - run:
#           name: test
#           command: mvn test
