version: 2.1

orbs:
    aws-cli: circleci/aws-cli@1.0
    aws-ecr: circleci/aws-ecr@6.12.2
    aws-ecs: circleci/aws-ecs@1.3.0
jobs:   
    run-task:
        docker:
            - image: maven:latest
            - image: redis:latest
        steps:
            - checkout
            - run:
                name: install
                command: mvn install
            - run:
                name: test
                command: mvn test
workflows:
    build-and-deploy:
        jobs:
            - run-task
            - aws-ecr/build-and-push-image:
                    repo: "${AWS_RESOURCE_NAME_PREFIX}"
                    tag: "latest"
                    requires:
                        - run-task
            - aws-ecs/deploy-service-update:
                    requires:
                        - aws-ecr/build-and-push-image
                    family: "${AWS_RESOURCE_NAME_PREFIX}-service"
                    cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
                    container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest"
                    verify-revision-is-deployed: true

        #    ea70889c76fa04c27253cf5c58f9c83b5c228ac2
        # 489173223852.dkr.ecr.us-east-1.amazonaws.com/spring-redis:ea70889c76fa04c27253cf5c58f9c83b5c228ac2


# - aws-ecs/run-task:
#         cluster: default
#         task-definition: first-run-task-definition
#         subnet-ids: "$SUBNET_ONE, $SUBNET_TWO"
#         security-group-ids: $SECURITY_GROUP_IDS
#         requires:
#             - aws-ecr/build-and-push-image