version: 2.1

orbs:
  maven: circleci/maven@0.0.12

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results

jobs:
  build:
    docker:
      - image: redis:latest
      - image: maven:latest 
    steps:
      - run: mvn clean install
      - run: mvn test
      